### ISSUE TITLE
SCOM 2019 - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TMacG123** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#31]
Hi - I'm getting the following error when trying to use your MP with SCOM 2019 (10.19.10407.0). 

I have the new SQL cumulative pack installed (7.0.24.0) and I also installed the 2014/2016 packs (7.0.15.0) when I read through some of the older issues (in case it still needs these for pre-requisites). This hasn't helped. Do you have any idea if it's compatible with SCOM 2019 as would be a killer MP for us to use.
Cheers. T.

![image](https://user-images.githubusercontent.com/80688125/111151100-e9d38f00-8586-11eb-8a61-62ef475ceafe.png)

**Comment by UretzkyZvi** [comment]
Hi,
Apologize, a short answer, I don't know. 
I'm not working with SCOM anymore, so it's difficult to say what the reason is.
As I see it, you can try to download the latest version of the MP https://martellotech.com/downloads/free-scom-management-packs/ and hope I solved it there, or you can ask these guys https://www.cookdown.com to pick up this MP.
