### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by michouser** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#7]
Great MP, looking forward to using, but for some reason the temples management pack is not included in the .msi file.  Wanted to know if this can be fixed.

**Comment by UretzkyZvi** [comment]
I will fix it.
Thanks

**Comment by michouser** [comment]
Sir,

I just did the install again of the MSI and there is still only two MPs.

Once you correct this problem, could you let me know?

It would be greatly apprecitated.

Thank you,

-Mike

**Comment by UretzkyZvi** [comment]
Of course, Last two nights I was working on several fixes and features improvements such as test button that will execute the test from the management server using scom agent permission instead of using client permission. I have some tests to complete I believe that today I wil publish new version with updated MSI release.. I will update you..

**Comment by UretzkyZvi** [comment]
Hi,
I had updated the msi with version 2.1.0.5.

Thank you,

**Comment by michouser** [comment]
Hi,

Just wanted to say thank you and it is greatly appreciated.

I am excited to try it out.

If I can be of any help, just let me know.

-Mike

**Comment by UretzkyZvi** [comment]
I need help with maintenance and future update, to be involved you are welcome to drop me a private message 

Thanks
